### ISSUE TITLE
Add "Opens in new window" text to links with `target="_blank"`

### ISSUE THREAD

**Issue by jeanfredrik** [whitespace-se/components#2]
The `<Link>` component should automatically add a visually hidden `<span>` with "Opens in new window" and an icon after the link text. This should be configurable globally but enabled by default.

**Comment by hinderson** [comment]
@Okkido Hittar tyvärr ingen bra ikon i Fluent Icons-paketet, så här behövs det lite UI-kärlek.

https://github.com/whitespace-se/components/commit/bdb2d07fae737c6b33f44bd28085ce07d6dbd86f
